### ISSUE TITLE
Change Readme - replace missing function

### ISSUE THREAD

**Issue by evolvedmicrobe** [mpkocher/pbcommandR#6]
Finally getting the chance to give this a whirl.  Two quick things came up:

One the readme suggests to just type 

    > library(testthat)
    > test()

But that doesn't really run tests from outside the project directory, perhaps it would be better to use:

    test_package("pbcommandR")

Which does run the tests, and unfortunately they fail due to an undefined function 'loginfo'  (see below).  I didn't see this function in the repo, should it be there?

 
    Sanity tests for ToolContract Registry Building: 456    

    Failed ----------------------------------------------------------
    1. Error: Simple example (@test.loadResolvedToolContract.R#7) ---
    could not find function "loginfo"
    1: loadResolvedToolContractFromPath(path) at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.loadResolvedToolContract.R:7    

    2. Error: Simple example (@test.loadToolContract.R#7) -----------
    could not find function "loginfo"
    1: loadToolContractFromPath(path) at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.loadToolContract.R:7
    2: dToToolContract(loadJsonFromFile(path))
    3: loadJsonFromFile(path)    

    3. Error: Convert TC to json (@test.loadToolContract.R#13) ------
    could not find function "loginfo"
    1: loadToolContractFromPath(path) at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.loadToolContract.R:13
    2: dToToolContract(loadJsonFromFile(path))
    3: loadJsonFromFile(path)    

    4. Error: Simple example (@test.sanityRegistry.R#13) ------------
    could not find function "loginfo"
    1: registryBuilder("pbcommandR", "Rscript /path/to/myExample.R run-rtc ") at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.sanityRegistry.R:13    

    5. Error: Registery Builder (@test.sanityRegistry.R#26) ---------
    could not find function "loginfo"
    1: registryBuilder("pbcommandR", "namespace") at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.sanityRegistry.R:26    

    6. Error: Registery Runner (@test.sanityRegistry.R#36) ----------
    could not find function "loginfo"
    1: exampleToolRegistryBuilder() at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbcommandR/tests/testthat/test.sanityRegistry.R:36
    2: registryBuilder(PB_TOOL_NAMESPACE, "exampleHelloWorld_R.sh run-rtc ")    

    DONE ============================================================
    Error: Test failures

**Comment by mpkocher** [comment]
I believe the loginfo func should be coming from the 'library(logging)' package. 

I was trying to use packrat in a python-ish virtualenv style. However, I don't think I ever really sorted out that worked.
